name: fizzleplugin
main: com.dorllenius.fizzleplugin.Plugin
version: 0.0.1
api-version: 1.15
description: Fizzle's Plugin For FUN!

commands: 
  scb:
    aliases: [test]
    description: This is my test command!
